var menuData=[
	{id:'home',icon:'icon-home',load:'',text:'首页',
		children:[
			{id:'homeHPC',icon:'icon-home',load:'template/HPC个人首页.html',text:'HPC个人首页'},
		  	{id:'homeopt',icon:'icon-home',load:'template/运维管理员首页.html',text:'运维首页'},
			{id:'homeopt1',icon:'icon-home',load:'template/集群性能指标.html',text:'集群性能指标'},
			{id:'homeopt2',icon:'icon-home',load:'template/业务首页.html',text:'业务首页'}
		]
	},
	{id:'jobControl',icon:'icon-th-list',load:'',text:'作业调度',
		children:[
			{id:'newjobUpdate',icon:'icon-chevron-right',load:'template/作业提交.html',text:'作业提交'},
			{id:'jobSystem',icon:'icon-chevron-right',load:'template/新作业系统.html',text:'新作业系统'},
			{id:'jobUpdate',icon:'icon-chevron-right',load:'template/基本提交.html',text:'基本提交'},
			{id:'portal',icon:'icon-chevron-right',load:'template/portal.html',text:'portal提交'},
		  	{id:'jobManage',icon:'icon-chevron-right',load:'template/作业管理.html',text:'作业管理'},
			{id:'jobHotMap',icon:'icon-chevron-right',load:'template/作业热图.html',text:'作业热图'},
			{id:'openVnc',icon:'icon-chevron-right',load:'template/打开VNC.html',text:'打开VNC'},
			{id:'vncManage',icon:'icon-chevron-right',load:'template/VNC查看.html',text:'VNC查看'},
			{id:'jobHistory',icon:'icon-chevron-right',load:'template/历史作业.html',text:'历史作业'},
			{id:'chartView',icon:'icon-chevron-right',load:'template/统计视图.html',text:'统计视图'},
			{id:'teamInfo',icon:'icon-chevron-right',load:'template/队列信息.html',text:'队列信息'},
			{id:'teamManagement',icon:'icon-chevron-right',load:'template/队列管理.html',text:'队列管理'},
			{id:'clientView',icon:'icon-chevron-right',load:'template/作业节点监控.html',text:'作业节点监控'},
			{id:'clientManagement',icon:'icon-chevron-right',load:'template/节点管理.html',text:'节点管理'},
			{id:'userSet',icon:'icon-chevron-right',load:'template/用户设置.html',text:'用户设置'},
			{id:'jobacount',icon:'icon-chevron-right',load:'template/作业记账.html',text:'作业记账'},
			{id:'ddManagement',icon:'icon-chevron-right',load:'template/调度器管理.html',text:'调度器管理'},
			{id:'account',icon:'icon-chevron-right',load:'template/账户管理.html',text:'账户管理'}
	  ]
	},
	{id:'groupMonitor',icon:'icon-dashboard',load:'',text:'集群监控',
		children:[
			{id:'linuxMonitor',icon:'icon-chevron-right',load:'template/linux单机.html',text:'Linux服务器'},
		  	{id:'winMonitor',icon:'icon-chevron-right',load:'template/linux单机.html',text:'win服务器'},
			{id:'groupMonitor1',icon:'icon-chevron-right',load:'template/物理视图.html',text:'物理视图'},
			{id:'groupMonitor21',icon:'icon-chevron-right',load:'template/新物理视图.html',text:'新物理视图'},
			{id:'groupMonitor2',icon:'icon-chevron-right',load:'template/热图.html',text:'热图'},
		  	{id:'groupMonitor3',icon:'icon-chevron-right',load:'template/分组视图.html',text:'分组视图'},
			{id:'groupMonitor4',icon:'icon-chevron-right',load:'template/性能对比.html',text:'性能对比'},
			{id:'groupMonitor5',icon:'icon-chevron-right',load:'template/网络拓扑.html',text:'网络拓扑'},
			{id:'groupMonitor6',icon:'icon-chevron-right',load:'template/SuperRack.html',text:'SuperRack'},
			{id:'groupMonitor8',icon:'icon-chevron-right',load:'template/报表系统.html',text:'报表系统'},
			{id:'groupMonitor9',icon:'icon-chevron-right',load:'template/交换机.html',text:'交换机'},
			{id:'groupMonitor10',icon:'icon-chevron-right',load:'template/刀片机箱.html',text:'刀片机箱'},
			{id:'groupMonitor11',icon:'icon-chevron-right',load:'template/刀片机箱4600.html',text:'刀片机箱4600'},
			{id:'groupMonitor12',icon:'icon-chevron-right',load:'template/虚拟机信息.html',text:'虚拟机信息'},
			{id:'groupMonitor13',icon:'icon-chevron-right',load:'template/盘阵管理.html',text:'盘阵管理'}
//		  	{id:'groupMonitor7',icon:'icon-chevron-right',load:'template/告警管理.html',text:'告警管理'}
	  ]
	},
	{id:'sysManagement',icon:'icon-cogs',load:'',text:'系统管理',
		children:[
			{id:'sysManagement1',icon:'icon-chevron-right',load:'template/用户管理.html',text:'平台用户管理'},
			{id:'sysManagement2',icon:'icon-chevron-right',load:'',text:'申请审批管理',children:
			[
			 	{id:'resource',icon:'icon-chevron-right',load:'template/资源申请.html',text:'资源申请'},
		   		{id:'query',icon:'icon-chevron-right',load:'template/申请查询.html',text:'申请查询'}
			]	
			},
		  {id:'sysManagement3',icon:'icon-chevron-right',load:'template/申请审批管理.html',text:'申请审批管理'},
		  {id:'sysManagement4',icon:'icon-chevron-right',load:'template/故障单查询.html',text:'故障单查询'},
		  {id:'sysManagement5',icon:'icon-chevron-right',load:'template/故障单管理.html',text:'故障单管理'},
		  {id:'sysManagement6',icon:'icon-chevron-right',load:'template/日志审计.html',text:'日志审计'},
		  {id:'sysManagement7',icon:'icon-chevron-right',load:'template/系统自维护.html',text:'系统自维护'}
	  ]
	},
	{id:'AlarmManagement',icon:'icon-cogs',load:'',text:'告警管理',
		children:[
			{id:'AlarmManagement1',icon:'icon-chevron-right',load:'template/告警概况.html',text:'告警概况'},
			{id:'AlarmManagement2',icon:'icon-chevron-right',load:'template/阈值管理.html',text:'阈值管理'},
			{id:'AlarmManagement3',icon:'icon-chevron-right',load:'template/策略管理.html',text:'策略管理'},
	  ]
	},
	{id:'clusterConfiguration',icon:'icon-sitemap',load:'',text:'集群配置',
		children:[
			{id:'clusterConfiguration1',icon:'icon-chevron-right',load:'template/一键配置集群.html',text:'一键配置集群'},
		  	{id:'clusterConfiguration2',icon:'icon-chevron-right',load:'template/NFS配置.html',text:'NFS配置'},
			{id:'clusterConfiguration3',icon:'icon-chevron-right',load:'template/NIS配置.html',text:'NIS配置'},
			{id:'clusterConfiguration4',icon:'icon-chevron-right',load:'template/SSHRSH配置.html',text:'SSH/RSH配置'},
			{id:'clusterConfiguration5',icon:'icon-chevron-right',load:'template/IPMI配置.html',text:'IPMI配置'},
			{id:'clusterConfiguration6',icon:'icon-chevron-right',load:'template/服务管理.html',text:'HPC相关服务'},
			{id:'clusterConfiguration7',icon:'icon-chevron-right',load:'template/时间同步.html',text:'时间同步'}
	  	]
	},
	{id:'clusterManagement',icon:'icon-qrcode',load:'',text:'集群管理',
		children:[
			{id:'clusterManagement0',icon:'icon-chevron-right',load:'template/集群部署.html',text:'集群部署'},
			{id:'clusterManagement1',icon:'icon-chevron-right',load:'template/OS用户管理.html',text:'OS用户管理'},
			{id:'clusterManagement7',icon:'icon-chevron-right',load:'template/性能评测.html',text:'性能评测'},
			{id:'clusterManagement2',icon:'icon-chevron-right',load:'template/常用功能.html',text:'常用功能'},
			{id:'clusterManagement3',icon:'icon-chevron-right',load:'template/磁盘配额管理.html',text:'磁盘配额管理'},
		  	{id:'clusterManagement4',icon:'icon-chevron-right',load:'template/批量开关机.html',text:'批量开关机'},
			{id:'clusterManagement5',icon:'icon-chevron-right',load:'',text:'VNC管理'},
			{id:'clusterManagement6',icon:'icon-chevron-right',load:'template/文件管理.html',text:'文件管理'}
	  	]
	},
	{id:'reportingSystem',icon:'icon-qrcode',load:'',text:'报表系统',
		children:[
			{id:'reportingSystem1',icon:'icon-chevron-right',load:'template/预定义报表.html',text:'预定义报表'},
			{id:'reportingSystem2',icon:'icon-chevron-right',load:'template/自定义报表.html',text:'自定义报表'}
	  	]
	},
	{id:'resourceManagement',icon:'icon-dropbox',load:'',text:'资源管理',
		children:[
			{id:'resourceManagement0',icon:'icon-chevron-right',load:'template/资源概况.html',text:'资源概况'},
			{id:'resourceManagement1',icon:'icon-chevron-right',load:'template/资源增加.html',text:'资源增加'},
			{id:'resourceManagement2',icon:'icon-chevron-right',load:'template/资源维护.html',text:'资源维护'},
		  	{id:'resourceManagement3',icon:'icon-chevron-right',load:'template/组资源管理.html',text:'组资源管理'},
			{id:'resourceManagement4',icon:'icon-chevron-right',load:'template/新资源管理.html',text:'新资源管理'}
	  	]
	},
	{id:'appManagement',icon:'icon-qrcode',load:'',text:'应用管理',
		children:[
			{id:'appManagement1',icon:'icon-chevron-right',load:'template/软件仓库.html',text:'软件仓库'},
			{id:'appManagement2',icon:'icon-chevron-right',load:'template/软件卸载.html',text:'软件卸载'}
	  	]
	},
	{id:'Plugin',icon:'icon-cogs',load:'',text:'组件显示',
		children:[
			{id:'window',icon:'icon-chevron-right',load:'template/winPlugin.html',text:'Window'},
			{id:'grid',icon:'icon-chevron-right',load:'template/gridPlugin.html',text:'Grid'},
			{id:'button',icon:'icon-chevron-right',load:'template/buttonPlugin.html',text:'Button'},
			{id:'formfield',icon:'icon-chevron-right',load:'template/form-field.html',text:'表单组件'},
			{id:'layout',icon:'icon-chevron-right',load:'',text:'布局',
				children:[
				  {id:'layoutTable',icon:'icon-chevron-right',load:'template/layoutTable.html',text:'Tabel布局'},
			      {id:'layoutColumn',icon:'icon-chevron-right',load:'template/layoutColumn.html',text:'Column空间'}
				]
				
				
			}
	  	]
		
	},
	{id:'domain',icon:'icon-cogs',load:'http://www.baidu.com domain',text:'跨域显示'},
	{id:'gridPanel',icon:'icon-cogs',load:'template/表格组件.html',text:'表格组件'},
	{id:'fileList',icon:'icon-cogs',load:'template/表格组件(文件列表).html',text:'文件列表'}
	];
$(function(){
	Gv.initLayout();
 	Gv.initEvent();
 	var tabId=Gv.getParaStr('tabId'),
 	     tabName=decodeURI(Gv.getParaStr('tabName')),
 	     load=decodeURI(Gv.getParaStr('load'));
	Gv.frameTabPanel=$(".frame-tab").Tab({items:[
	 {text:'业务首页',closed:true,icon:'',html:'',load:'template/业务首页.html',callback:function(){}}
	],
	width:Gv.clientW-this.frameNavWidth,
	height:$('#container').height(),
	});
	if(!Gv.isEmpty(tabId)){
		Gv.frameTabPanel.addTab({id:tabId,text:tabName,closed:true,icon:'',html:'',load:load,callback:function(){}});
 	}
	
	//右侧导航
  Gv.frameNavPanel=new Gv.panel.AccordionPanel({
		renderTo:'frame-nav-body',
		handler:function(r){
			Gv.frameTabPanel.addTab({id:r.id,text:r.text,closed:true,icon:'',html:r.html,load:r.load,callback:function(){}});
		},
		//url:'actioUrl',动态取值的路径
		data	:menuData//静态数据
		});
  
});