var callingcgs = [{
	"List": [{
		"List": [{
			"List": null,
			"Id": 4,
			"Name": "user011",
			"ParentId": 3,
			"Depth": 3,
			"PinYin": "canju",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "5,6,3,11,4,8,12",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "user011",
			"PrivateTradeId": 5,
			"PrivateTradeEntity": {
				"Id": 5,
				"Name": "user011",
				"AsynProcessingStatus": 0,
				"CategoryId": 4,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 33,
			"Name": "user012",
			"ParentId": 3,
			"Depth": 3,
			"PinYin": "kafeiju",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "user012",
			"PrivateTradeId": 64,
			"PrivateTradeEntity": {
				"Id": 64,
				"Name": "user012",
				"AsynProcessingStatus": 0,
				"CategoryId": 33,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 34,
			"Name": "user013",
			"ParentId": 3,
			"Depth": 3,
			"PinYin": "rongqi",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "user013",
			"PrivateTradeId": 66,
			"PrivateTradeEntity": {
				"Id": 66,
				"Name": "user013",
				"AsynProcessingStatus": 0,
				"CategoryId": 34,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 35,
			"Name": "user014",
			"ParentId": 3,
			"Depth": 3,
			"PinYin": "jiuju",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "user014",
			"PrivateTradeId": 68,
			"PrivateTradeEntity": {
				"Id": 68,
				"Name": "user014",
				"AsynProcessingStatus": 0,
				"CategoryId": 35,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 36,
			"Name": "茶具",
			"ParentId": 3,
			"Depth": 3,
			"PinYin": "chaju",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,9,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "茶具",
			"PrivateTradeId": 70,
			"PrivateTradeEntity": {
				"Id": 70,
				"Name": "茶具",
				"AsynProcessingStatus": 0,
				"CategoryId": 36,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 37,
			"Name": "其他日用陶瓷",
			"ParentId": 3,
			"Depth": 3,
			"PinYin": "qitariyongtaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,13,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "其他日用陶瓷",
			"PrivateTradeId": 72,
			"PrivateTradeEntity": {
				"Id": 72,
				"Name": "其他日用陶瓷",
				"AsynProcessingStatus": 0,
				"CategoryId": 37,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 10000,
				"PositionSettingType": 1,
				"MemberPosition": 10000,
				"MemberPositionSettingType": 1
			}
		}],
		"Id": 3,
		"Name": "group001",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "riyongtaoci",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "1,5,2,3,7,11,4,8,12",
		"IsExistsChildrenNodes": true,
		"PrivateTradeName": "group001",
		"PrivateTradeId": 3,
		"PrivateTradeEntity": {
			"Id": 3,
			"Name": "group001",
			"AsynProcessingStatus": 0,
			"CategoryId": 3,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 1,
			"PositionSettingType": 1,
			"MemberPosition": 1,
			"MemberPositionSettingType": 1
		}
	},
	{
		"List": [{
			"List": null,
			"Id": 38,
			"Name": "user021",
			"ParentId": 32,
			"Depth": 3,
			"PinYin": "yishutaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,9,6,3,7,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "user021",
			"PrivateTradeId": 73,
			"PrivateTradeEntity": {
				"Id": 73,
				"Name": "user021",
				"AsynProcessingStatus": 0,
				"CategoryId": 38,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 39,
			"Name": "user022",
			"ParentId": 32,
			"Depth": 3,
			"PinYin": "yuanlintaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,13,6,3,7,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "user022",
			"PrivateTradeId": 74,
			"PrivateTradeEntity": {
				"Id": 74,
				"Name": "user022",
				"AsynProcessingStatus": 0,
				"CategoryId": 39,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 40,
			"Name": "user023",
			"ParentId": 32,
			"Depth": 3,
			"PinYin": "liulizhipin",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,13,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "user023",
			"PrivateTradeId": 75,
			"PrivateTradeEntity": {
				"Id": 75,
				"Name": "user023",
				"AsynProcessingStatus": 0,
				"CategoryId": 40,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 41,
			"Name": "其他工艺陶瓷",
			"ParentId": 32,
			"Depth": 3,
			"PinYin": "qitagongyitaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,2,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "其他工艺陶瓷",
			"PrivateTradeId": 76,
			"PrivateTradeEntity": {
				"Id": 76,
				"Name": "其他工艺陶瓷",
				"AsynProcessingStatus": 0,
				"CategoryId": 41,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 10000,
				"PositionSettingType": 1,
				"MemberPosition": 10000,
				"MemberPositionSettingType": 1
			}
		}],
		"Id": 32,
		"Name": "group002",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "gongyitaoci",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "1,13,6,3",
		"IsExistsChildrenNodes": true,
		"PrivateTradeName": "group002",
		"PrivateTradeId": 62,
		"PrivateTradeEntity": {
			"Id": 62,
			"Name": "group002",
			"AsynProcessingStatus": 0,
			"CategoryId": 32,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 2,
			"PositionSettingType": 1,
			"MemberPosition": 2,
			"MemberPositionSettingType": 1
		}
	},
	{
		"List": [{
			"List": null,
			"Id": 43,
			"Name": "user031",
			"ParentId": 42,
			"Depth": 3,
			"PinYin": "neiqiangzhuan",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,9,13,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "user031",
			"PrivateTradeId": 79,
			"PrivateTradeEntity": {
				"Id": 79,
				"Name": "user031",
				"AsynProcessingStatus": 0,
				"CategoryId": 43,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 44,
			"Name": "user032",
			"ParentId": 42,
			"Depth": 3,
			"PinYin": "waiqiangzhuan",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,9,13,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "user032",
			"PrivateTradeId": 80,
			"PrivateTradeEntity": {
				"Id": 80,
				"Name": "user032",
				"AsynProcessingStatus": 0,
				"CategoryId": 44,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 45,
			"Name": "user033",
			"ParentId": 42,
			"Depth": 3,
			"PinYin": "dimianzhuan",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,9",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "user033",
			"PrivateTradeId": 81,
			"PrivateTradeEntity": {
				"Id": 81,
				"Name": "user033",
				"AsynProcessingStatus": 0,
				"CategoryId": 45,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 46,
			"Name": "user034",
			"ParentId": 42,
			"Depth": 3,
			"PinYin": "guangchangzhuan",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,9,13",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "user034",
			"PrivateTradeId": 82,
			"PrivateTradeEntity": {
				"Id": 82,
				"Name": "user034",
				"AsynProcessingStatus": 0,
				"CategoryId": 46,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 47,
			"Name": "文化石",
			"ParentId": 42,
			"Depth": 3,
			"PinYin": "wenhuashi",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,9,13,6,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "文化石",
			"PrivateTradeId": 83,
			"PrivateTradeEntity": {
				"Id": 83,
				"Name": "文化石",
				"AsynProcessingStatus": 0,
				"CategoryId": 47,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 48,
			"Name": "瓷片",
			"ParentId": 42,
			"Depth": 3,
			"PinYin": "cipian",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,9,13,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "瓷片",
			"PrivateTradeId": 84,
			"PrivateTradeEntity": {
				"Id": 84,
				"Name": "瓷片",
				"AsynProcessingStatus": 0,
				"CategoryId": 48,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 49,
			"Name": "拼花",
			"ParentId": 42,
			"Depth": 3,
			"PinYin": "pinhua",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,9,13,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "拼花",
			"PrivateTradeId": 85,
			"PrivateTradeEntity": {
				"Id": 85,
				"Name": "拼花",
				"AsynProcessingStatus": 0,
				"CategoryId": 49,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 50,
			"Name": "釉面砖",
			"ParentId": 42,
			"Depth": 3,
			"PinYin": "youmianzhuan",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,9,13,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "釉面砖",
			"PrivateTradeId": 86,
			"PrivateTradeEntity": {
				"Id": 86,
				"Name": "釉面砖",
				"AsynProcessingStatus": 0,
				"CategoryId": 50,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 51,
			"Name": "通体砖",
			"ParentId": 42,
			"Depth": 3,
			"PinYin": "tongtizhuan",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,9,13,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "通体砖",
			"PrivateTradeId": 87,
			"PrivateTradeEntity": {
				"Id": 87,
				"Name": "通体砖",
				"AsynProcessingStatus": 0,
				"CategoryId": 51,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 52,
			"Name": "仿古砖",
			"ParentId": 42,
			"Depth": 3,
			"PinYin": "fangguzhuan",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,9,13,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "仿古砖",
			"PrivateTradeId": 88,
			"PrivateTradeEntity": {
				"Id": 88,
				"Name": "仿古砖",
				"AsynProcessingStatus": 0,
				"CategoryId": 52,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 54,
			"Name": "马赛克",
			"ParentId": 42,
			"Depth": 3,
			"PinYin": "masaiketaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,9,13,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "马赛克",
			"PrivateTradeId": 89,
			"PrivateTradeEntity": {
				"Id": 89,
				"Name": "马赛克",
				"AsynProcessingStatus": 0,
				"CategoryId": 54,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 55,
			"Name": "琉璃瓦",
			"ParentId": 42,
			"Depth": 3,
			"PinYin": "liuliw",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,9,13,2,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "琉璃瓦",
			"PrivateTradeId": 90,
			"PrivateTradeEntity": {
				"Id": 90,
				"Name": "琉璃瓦",
				"AsynProcessingStatus": 0,
				"CategoryId": 55,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 2382,
			"Name": "腰线",
			"ParentId": 42,
			"Depth": 3,
			"PinYin": "yaoxian",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,6,3,7",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "腰线",
			"PrivateTradeId": 2826,
			"PrivateTradeEntity": {
				"Id": 2826,
				"Name": "腰线",
				"AsynProcessingStatus": 0,
				"CategoryId": 2382,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 57,
			"Name": "其他建筑陶瓷",
			"ParentId": 42,
			"Depth": 3,
			"PinYin": "qitajianzhutaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,9,13,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "其他建筑陶瓷",
			"PrivateTradeId": 93,
			"PrivateTradeEntity": {
				"Id": 93,
				"Name": "其他建筑陶瓷",
				"AsynProcessingStatus": 0,
				"CategoryId": 57,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 10000,
				"PositionSettingType": 1,
				"MemberPosition": 10000,
				"MemberPositionSettingType": 1
			}
		}],
		"Id": 42,
		"Name": "group003",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "jianzhutaoci",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "1,5,13,2,6,3,4",
		"IsExistsChildrenNodes": true,
		"PrivateTradeName": "group003",
		"PrivateTradeId": 77,
		"PrivateTradeEntity": {
			"Id": 77,
			"Name": "group003",
			"AsynProcessingStatus": 0,
			"CategoryId": 42,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 3,
			"PositionSettingType": 1,
			"MemberPosition": 3,
			"MemberPositionSettingType": 1
		}
	},
	{
		"List": [{
			"List": null,
			"Id": 60,
			"Name": "浴缸",
			"ParentId": 59,
			"Depth": 3,
			"PinYin": "yugang",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "浴缸",
			"PrivateTradeId": 98,
			"PrivateTradeEntity": {
				"Id": 98,
				"Name": "浴缸",
				"AsynProcessingStatus": 0,
				"CategoryId": 60,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 61,
			"Name": "淋浴房",
			"ParentId": 59,
			"Depth": 3,
			"PinYin": "linyufan",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "淋浴房",
			"PrivateTradeId": 99,
			"PrivateTradeEntity": {
				"Id": 99,
				"Name": "淋浴房",
				"AsynProcessingStatus": 0,
				"CategoryId": 61,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 62,
			"Name": "洗脸器",
			"ParentId": 59,
			"Depth": 3,
			"PinYin": "xilianqi",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "洗脸器",
			"PrivateTradeId": 100,
			"PrivateTradeEntity": {
				"Id": 100,
				"Name": "洗脸器",
				"AsynProcessingStatus": 0,
				"CategoryId": 62,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 66,
			"Name": "便器",
			"ParentId": 59,
			"Depth": 3,
			"PinYin": "bianqi",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "便器",
			"PrivateTradeId": 107,
			"PrivateTradeEntity": {
				"Id": 107,
				"Name": "便器",
				"AsynProcessingStatus": 0,
				"CategoryId": 66,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 68,
			"Name": "洗涤器",
			"ParentId": 59,
			"Depth": 3,
			"PinYin": "xidiqi",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "洗涤器",
			"PrivateTradeId": 110,
			"PrivateTradeEntity": {
				"Id": 110,
				"Name": "洗涤器",
				"AsynProcessingStatus": 0,
				"CategoryId": 68,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 70,
			"Name": "卫浴配件",
			"ParentId": 59,
			"Depth": 3,
			"PinYin": "weiyupeijian",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,9,13,21,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "卫浴配件",
			"PrivateTradeId": 113,
			"PrivateTradeEntity": {
				"Id": 113,
				"Name": "卫浴配件",
				"AsynProcessingStatus": 0,
				"CategoryId": 70,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 74,
			"Name": "水龙头阀门",
			"ParentId": 59,
			"Depth": 3,
			"PinYin": "shuilongtoufamen",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "5,21,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "水龙头阀门",
			"PrivateTradeId": 120,
			"PrivateTradeEntity": {
				"Id": 120,
				"Name": "水龙头阀门",
				"AsynProcessingStatus": 0,
				"CategoryId": 74,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 76,
			"Name": "整体浴室",
			"ParentId": 59,
			"Depth": 3,
			"PinYin": "zhengtiyushi",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "5,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "整体浴室",
			"PrivateTradeId": 123,
			"PrivateTradeEntity": {
				"Id": 123,
				"Name": "整体浴室",
				"AsynProcessingStatus": 0,
				"CategoryId": 76,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 86,
			"Name": "其他卫浴陶瓷",
			"ParentId": 59,
			"Depth": 3,
			"PinYin": "qitaweiyutaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,5,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "其他卫浴陶瓷",
			"PrivateTradeId": 142,
			"PrivateTradeEntity": {
				"Id": 142,
				"Name": "其他卫浴陶瓷",
				"AsynProcessingStatus": 0,
				"CategoryId": 86,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 10000,
				"PositionSettingType": 1,
				"MemberPosition": 10000,
				"MemberPositionSettingType": 1
			}
		}],
		"Id": 59,
		"Name": "卫浴陶瓷",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "weiyutaoci",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "1,5,6,3,4",
		"IsExistsChildrenNodes": true,
		"PrivateTradeName": "卫浴陶瓷",
		"PrivateTradeId": 96,
		"PrivateTradeEntity": {
			"Id": 96,
			"Name": "卫浴陶瓷",
			"AsynProcessingStatus": 0,
			"CategoryId": 59,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 4,
			"PositionSettingType": 1,
			"MemberPosition": 4,
			"MemberPositionSettingType": 1
		}
	},
	{
		"List": [{
			"List": null,
			"Id": 90,
			"Name": "电子陶瓷",
			"ParentId": 88,
			"Depth": 3,
			"PinYin": "dianzitaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "电子陶瓷",
			"PrivateTradeId": 149,
			"PrivateTradeEntity": {
				"Id": 149,
				"Name": "电子陶瓷",
				"AsynProcessingStatus": 0,
				"CategoryId": 90,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 93,
			"Name": "蜂窝陶瓷",
			"ParentId": 88,
			"Depth": 3,
			"PinYin": "fengwotaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "蜂窝陶瓷",
			"PrivateTradeId": 154,
			"PrivateTradeEntity": {
				"Id": 154,
				"Name": "蜂窝陶瓷",
				"AsynProcessingStatus": 0,
				"CategoryId": 93,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 95,
			"Name": "工程陶瓷",
			"ParentId": 88,
			"Depth": 3,
			"PinYin": "gongchengtaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "工程陶瓷",
			"PrivateTradeId": 156,
			"PrivateTradeEntity": {
				"Id": 156,
				"Name": "工程陶瓷",
				"AsynProcessingStatus": 0,
				"CategoryId": 95,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 98,
			"Name": "化工陶瓷",
			"ParentId": 88,
			"Depth": 3,
			"PinYin": "huagongtaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "化工陶瓷",
			"PrivateTradeId": 160,
			"PrivateTradeEntity": {
				"Id": 160,
				"Name": "化工陶瓷",
				"AsynProcessingStatus": 0,
				"CategoryId": 98,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 104,
			"Name": "电器瓷",
			"ParentId": 88,
			"Depth": 3,
			"PinYin": "dianqici",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "电器瓷",
			"PrivateTradeId": 168,
			"PrivateTradeEntity": {
				"Id": 168,
				"Name": "电器瓷",
				"AsynProcessingStatus": 0,
				"CategoryId": 104,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 110,
			"Name": "耐火研磨陶瓷",
			"ParentId": 88,
			"Depth": 3,
			"PinYin": "naihuoyanmotaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "耐火研磨陶瓷",
			"PrivateTradeId": 176,
			"PrivateTradeEntity": {
				"Id": 176,
				"Name": "耐火研磨陶瓷",
				"AsynProcessingStatus": 0,
				"CategoryId": 110,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 124,
			"Name": "功能陶瓷配件",
			"ParentId": 88,
			"Depth": 3,
			"PinYin": "gonnengtaocipeijian",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3,4",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "功能陶瓷配件",
			"PrivateTradeId": 195,
			"PrivateTradeEntity": {
				"Id": 195,
				"Name": "功能陶瓷配件",
				"AsynProcessingStatus": 0,
				"CategoryId": 124,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 131,
			"Name": "工业琉璃",
			"ParentId": 88,
			"Depth": 3,
			"PinYin": "gongyeliuli",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "13,2,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "工业琉璃",
			"PrivateTradeId": 203,
			"PrivateTradeEntity": {
				"Id": 203,
				"Name": "工业琉璃",
				"AsynProcessingStatus": 0,
				"CategoryId": 131,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 135,
			"Name": "其他工业陶瓷",
			"ParentId": 88,
			"Depth": 3,
			"PinYin": "qitagongyetaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "其他工业陶瓷",
			"PrivateTradeId": 208,
			"PrivateTradeEntity": {
				"Id": 208,
				"Name": "其他工业陶瓷",
				"AsynProcessingStatus": 0,
				"CategoryId": 135,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 10000,
				"PositionSettingType": 1,
				"MemberPosition": 10000,
				"MemberPositionSettingType": 1
			}
		}],
		"Id": 88,
		"Name": "工业陶瓷",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "gongyetaoci",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "1,13,6,3",
		"IsExistsChildrenNodes": true,
		"PrivateTradeName": "工业陶瓷",
		"PrivateTradeId": 145,
		"PrivateTradeEntity": {
			"Id": 145,
			"Name": "工业陶瓷",
			"AsynProcessingStatus": 0,
			"CategoryId": 88,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 5,
			"PositionSettingType": 1,
			"MemberPosition": 5,
			"MemberPositionSettingType": 1
		}
	},
	{
		"List": [{
			"List": null,
			"Id": 143,
			"Name": "功能陶瓷",
			"ParentId": 139,
			"Depth": 3,
			"PinYin": "gongnengtaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "功能陶瓷",
			"PrivateTradeId": 218,
			"PrivateTradeEntity": {
				"Id": 218,
				"Name": "功能陶瓷",
				"AsynProcessingStatus": 0,
				"CategoryId": 143,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 146,
			"Name": "结构陶瓷",
			"ParentId": 139,
			"Depth": 3,
			"PinYin": "jiegoutaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "结构陶瓷",
			"PrivateTradeId": 223,
			"PrivateTradeEntity": {
				"Id": 223,
				"Name": "结构陶瓷",
				"AsynProcessingStatus": 0,
				"CategoryId": 146,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 149,
			"Name": "其他特种陶瓷",
			"ParentId": 139,
			"Depth": 3,
			"PinYin": "qitatezhongtaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "其他特种陶瓷",
			"PrivateTradeId": 226,
			"PrivateTradeEntity": {
				"Id": 226,
				"Name": "其他特种陶瓷",
				"AsynProcessingStatus": 0,
				"CategoryId": 149,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 10000,
				"PositionSettingType": 1,
				"MemberPosition": 10000,
				"MemberPositionSettingType": 1
			}
		}],
		"Id": 139,
		"Name": "group1",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "tezhongtaoci",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "5,9,13,6,3",
		"IsExistsChildrenNodes": true,
		"PrivateTradeName": "group1",
		"PrivateTradeId": 213,
		"PrivateTradeEntity": {
			"Id": 213,
			"Name": "group1",
			"AsynProcessingStatus": 0,
			"CategoryId": 139,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 6,
			"PositionSettingType": 1,
			"MemberPosition": 6,
			"MemberPositionSettingType": 1
		}
	},
	{
		"List": [{
			"List": null,
			"Id": 163,
			"Name": "陶瓷岩",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "taociyan",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "2,3,4,8",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "陶瓷岩",
			"PrivateTradeId": 242,
			"PrivateTradeEntity": {
				"Id": 242,
				"Name": "陶瓷岩",
				"AsynProcessingStatus": 0,
				"CategoryId": 163,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 168,
			"Name": "膨润土",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "pengrunt",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,8",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "膨润土",
			"PrivateTradeId": 247,
			"PrivateTradeEntity": {
				"Id": 247,
				"Name": "膨润土",
				"AsynProcessingStatus": 0,
				"CategoryId": 168,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 171,
			"Name": "球土",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "qiutuu",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,8",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "球土",
			"PrivateTradeId": 250,
			"PrivateTradeEntity": {
				"Id": 250,
				"Name": "球土",
				"AsynProcessingStatus": 0,
				"CategoryId": 171,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 176,
			"Name": "陶瓷土",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "taocitu",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,8",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "陶瓷土",
			"PrivateTradeId": 255,
			"PrivateTradeEntity": {
				"Id": 255,
				"Name": "陶瓷土",
				"AsynProcessingStatus": 0,
				"CategoryId": 176,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 180,
			"Name": "锂云母",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "liyun",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "2,8",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "锂云母",
			"PrivateTradeId": 259,
			"PrivateTradeEntity": {
				"Id": 259,
				"Name": "锂云母",
				"AsynProcessingStatus": 0,
				"CategoryId": 180,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 185,
			"Name": "绢云母",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "yunmu",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,13,6,3",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "绢云母",
			"PrivateTradeId": 264,
			"PrivateTradeEntity": {
				"Id": 264,
				"Name": "绢云母",
				"AsynProcessingStatus": 0,
				"CategoryId": 185,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 189,
			"Name": "粘土",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "niantu",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1,8",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "粘土",
			"PrivateTradeId": 268,
			"PrivateTradeEntity": {
				"Id": 268,
				"Name": "粘土",
				"AsynProcessingStatus": 0,
				"CategoryId": 189,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 194,
			"Name": "伊利石",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "yilishi",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "2,8",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "伊利石",
			"PrivateTradeId": 273,
			"PrivateTradeEntity": {
				"Id": 273,
				"Name": "伊利石",
				"AsynProcessingStatus": 0,
				"CategoryId": 194,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 199,
			"Name": "硅灰石",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "guihui",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "8",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "硅灰石",
			"PrivateTradeId": 278,
			"PrivateTradeEntity": {
				"Id": 278,
				"Name": "硅灰石",
				"AsynProcessingStatus": 0,
				"CategoryId": 199,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 202,
			"Name": "叶腊石",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "yela",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "8",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "叶腊石",
			"PrivateTradeId": 281,
			"PrivateTradeEntity": {
				"Id": 281,
				"Name": "叶腊石",
				"AsynProcessingStatus": 0,
				"CategoryId": 202,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 204,
			"Name": "石英",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "shiyi",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "8",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "石英",
			"PrivateTradeId": 283,
			"PrivateTradeEntity": {
				"Id": 283,
				"Name": "石英",
				"AsynProcessingStatus": 0,
				"CategoryId": 204,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 206,
			"Name": "超白粉",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "whitepowder",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "8",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "超白粉",
			"PrivateTradeId": 286,
			"PrivateTradeEntity": {
				"Id": 286,
				"Name": "超白粉",
				"AsynProcessingStatus": 0,
				"CategoryId": 206,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 211,
			"Name": "萤石",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "yingshi",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "8",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "萤石",
			"PrivateTradeId": 291,
			"PrivateTradeEntity": {
				"Id": 291,
				"Name": "萤石",
				"AsynProcessingStatus": 0,
				"CategoryId": 211,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 221,
			"Name": "滑石",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "huas",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "2,8",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "滑石",
			"PrivateTradeId": 303,
			"PrivateTradeEntity": {
				"Id": 303,
				"Name": "滑石",
				"AsynProcessingStatus": 0,
				"CategoryId": 221,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 224,
			"Name": "长石",
			"ParentId": 153,
			"Depth": 3,
			"PinYin": "feldspar",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "2,8",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "长石",
			"PrivateTradeId": 306,
			"PrivateTradeEntity": {
				"Id": 306,
				"Name": "长石",
				"AsynProcessingStatus": 0,
				"CategoryId": 224,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		}],
		"Id": 153,
		"Name": "group2",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "taociyuanliao",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "13,2,6,3",
		"IsExistsChildrenNodes": true,
		"PrivateTradeName": "group2",
		"PrivateTradeId": 230,
		"PrivateTradeEntity": {
			"Id": 230,
			"Name": "group2",
			"AsynProcessingStatus": 0,
			"CategoryId": 153,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 7,
			"PositionSettingType": 1,
			"MemberPosition": 7,
			"MemberPositionSettingType": 1
		}
	},
	{
		"List": null,
		"Id": 230,
		"Name": "陶瓷釉料",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "taociyouliao",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "1,13,6,3",
		"IsExistsChildrenNodes": false,
		"PrivateTradeName": "陶瓷釉料",
		"PrivateTradeId": 313,
		"PrivateTradeEntity": {
			"Id": 313,
			"Name": "陶瓷釉料",
			"AsynProcessingStatus": 0,
			"CategoryId": 230,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 1000,
			"PositionSettingType": 0,
			"MemberPosition": 1000,
			"MemberPositionSettingType": 0
		}
	},
	{
		"List": null,
		"Id": 231,
		"Name": "陶瓷颜料",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "taociliao",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "1,6,11,12",
		"IsExistsChildrenNodes": false,
		"PrivateTradeName": "陶瓷颜料",
		"PrivateTradeId": 315,
		"PrivateTradeEntity": {
			"Id": 315,
			"Name": "陶瓷颜料",
			"AsynProcessingStatus": 0,
			"CategoryId": 231,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 1000,
			"PositionSettingType": 0,
			"MemberPosition": 1000,
			"MemberPositionSettingType": 0
		}
	},
	{
		"List": null,
		"Id": 234,
		"Name": "陶瓷色料",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "taociseliao",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "1,6,8,12",
		"IsExistsChildrenNodes": false,
		"PrivateTradeName": "陶瓷色料",
		"PrivateTradeId": 320,
		"PrivateTradeEntity": {
			"Id": 320,
			"Name": "陶瓷色料",
			"AsynProcessingStatus": 0,
			"CategoryId": 234,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 1000,
			"PositionSettingType": 0,
			"MemberPosition": 1000,
			"MemberPositionSettingType": 0
		}
	},
	{
		"List": null,
		"Id": 241,
		"Name": "陶瓷熔块",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "taocirongkuai",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "9,13,8,12",
		"IsExistsChildrenNodes": false,
		"PrivateTradeName": "陶瓷熔块",
		"PrivateTradeId": 334,
		"PrivateTradeEntity": {
			"Id": 334,
			"Name": "陶瓷熔块",
			"AsynProcessingStatus": 0,
			"CategoryId": 241,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 1000,
			"PositionSettingType": 0,
			"MemberPosition": 1000,
			"MemberPositionSettingType": 0
		}
	},
	{
		"List": null,
		"Id": 245,
		"Name": "用户组10",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "taocifuliao",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "1,6,3,11,15,8,12",
		"IsExistsChildrenNodes": false,
		"PrivateTradeName": "用户组9",
		"PrivateTradeId": 341,
		"PrivateTradeEntity": {
			"Id": 341,
			"Name": "用户组9",
			"AsynProcessingStatus": 0,
			"CategoryId": 245,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 1000,
			"PositionSettingType": 0,
			"MemberPosition": 1000,
			"MemberPositionSettingType": 0
		}
	},
	{
		"List": null,
		"Id": 249,
		"Name": "用户组8",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "taocirongji",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "6,14,11,15,8,12",
		"IsExistsChildrenNodes": false,
		"PrivateTradeName": "用户组8",
		"PrivateTradeId": 348,
		"PrivateTradeEntity": {
			"Id": 348,
			"Name": "用户组8",
			"AsynProcessingStatus": 0,
			"CategoryId": 249,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 1000,
			"PositionSettingType": 0,
			"MemberPosition": 1000,
			"MemberPositionSettingType": 0

		}
	},
	{
		"List": null,
		"Id": 255,
		"Name": "用户组7",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "taocinengyuan",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "1,13,6,14,3,11,15,8,12",
		"IsExistsChildrenNodes": false,
		"PrivateTradeName": "用户组7",
		"PrivateTradeId": 355,
		"PrivateTradeEntity": {
			"Id": 355,
			"Name": "用户组7",
			"AsynProcessingStatus": 0,
			"CategoryId": 255,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 1000,
			"PositionSettingType": 0,
			"MemberPosition": 1000,
			"MemberPositionSettingType": 0
		}
	},
	{
		"List": [{
			"List": null,
			"Id": 1235,
			"Name": "用户6",
			"ParentId": 1234,
			"Depth": 3,
			"PinYin": "guangmiantaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "用户6",
			"PrivateTradeId": 1496,
			"PrivateTradeEntity": {
				"Id": 1496,
				"Name": "用户6",
				"AsynProcessingStatus": 0,
				"CategoryId": 1235,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		},
		{
			"List": null,
			"Id": 1249,
			"Name": "用户组4",
			"ParentId": 1234,
			"Depth": 3,
			"PinYin": "yamiantaoci",
			"OldId": 0,
			"CategoryTypeId": 1,
			"AsynProcessingStatus": 0,
			"MeasurementUnits": "1",
			"IsExistsChildrenNodes": false,
			"PrivateTradeName": "用户组4",
			"PrivateTradeId": 1510,
			"PrivateTradeEntity": {
				"Id": 1510,
				"Name": "用户组4",
				"AsynProcessingStatus": 0,
				"CategoryId": 1249,
				"TradeTypeId": 1,
				"IsScreening": true,
				"Position": 1000,
				"PositionSettingType": 0,
				"MemberPosition": 1000,
				"MemberPositionSettingType": 0
			}
		}],
		"Id": 1234,
		"Name": "用户组3",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "taocimasaike",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "1",
		"IsExistsChildrenNodes": true,
		"PrivateTradeName": "用户组3",
		"PrivateTradeId": 1495,
		"PrivateTradeEntity": {
			"Id": 1495,
			"Name": "用户组3",
			"AsynProcessingStatus": 0,
			"CategoryId": 1234,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 1000,
			"PositionSettingType": 0,
			"MemberPosition": 1000,
			"MemberPositionSettingType": 0
		}
	},
	{
		"List": null,
		"Id": 1751,
		"Name": "用户组2",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "taocigognyipin",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "5,9,13,3,7,4",
		"IsExistsChildrenNodes": false,
		"PrivateTradeName": "用户组2",
		"PrivateTradeId": 2066,
		"PrivateTradeEntity": {
			"Id": 2066,
			"Name": "用户组2",
			"AsynProcessingStatus": 0,
			"CategoryId": 1751,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 1000,
			"PositionSettingType": 0,
			"MemberPosition": 1000,
			"MemberPositionSettingType": 0
		}
	},
	{
		"List": null,
		"Id": 259,
		"Name": "用户组1",
		"ParentId": 1,
		"Depth": 2,
		"PinYin": "qitataociyuanliao",
		"OldId": 0,
		"CategoryTypeId": 1,
		"AsynProcessingStatus": 0,
		"MeasurementUnits": "1,5,9,13,6,3",
		"IsExistsChildrenNodes": false,
		"PrivateTradeName": "用户组1",
		"PrivateTradeId": 361,
		"PrivateTradeEntity": {
			"Id": 361,
			"Name": "用户组1",
			"AsynProcessingStatus": 0,
			"CategoryId": 259,
			"TradeTypeId": 1,
			"IsScreening": true,
			"Position": 10000,
			"PositionSettingType": 1,
			"MemberPosition": 10000,
			"MemberPositionSettingType": 1
		}
	}],
	"Id": 1,
	"Name": "节点1",
	"ParentId": 0,
	"Depth": 1,
	"PinYin": "taoci",
	"OldId": 0,
	"CategoryTypeId": 1,
	"AsynProcessingStatus": 0,
	"MeasurementUnits": "1,5,2,6,3,11,4,8,12",
	"IsExistsChildrenNodes": true,
	"PrivateTradeName": "节点1",
	"PrivateTradeId": 1,
	"PrivateTradeEntity": {
		"Id": 1,
		"Name": "节点1",
		"AsynProcessingStatus": 0,
		"CategoryId": 1,
		"TradeTypeId": 1,
		"IsScreening": true,
		"Position": 1,
		"PositionSettingType": 1,
		"MemberPosition": 1,
		"MemberPositionSettingType": 1
	}
}];